import React, {useState} from 'react'

const Breeds = {
    Dog: [
      "German Shepherd",
      "Bulldog",
      
    ],
    Cat: [
      "Siamese cat",
      "British Shorthair",
      "Maine Coon",
      "Persian Cat",
      "Ragdoll",
      "Sphynx cat",
      "American Shorthair",
      "Abyssinian",
      "Exotic Shorthair",
      "Scottish fold",
      "Burmese Cat",
      "Birman",
      "Bombay Cat",
      "Siberian Cat",
      "Norwegian Forest Cat",
      "Russian Blue",
    ],
    Horse: [
      "Arabian Horse",
      "Marwari Horse",
      "Andalusian Horse",
      "Friesian Horse",
      "Akhal-Teke Horse",
      "Gypsy Vanner Horse",
      "Haflinger Horse",
      "Appaloosa Horse",
      "Paso Fino Horse",
      "Mustang Horse",
    ],
    Fish: [
      "The Betta",
      "Freshwater Angelfish",
      "Fancy Guppies",
      "Mollies",
      "Tiger Barbs",
      "Oscars",
      "Ocellaris Clownfish",
      "Convict Cichlids",
      "Mbuna Cichlids",
      "Fancy Goldfish",
    ],
    Bird: [
      "Canary",
      "Budgerigar",
      "Cockatiel",
      "Cockatoo",
      "Hyacinth Macaw",
      "Dove",
      "Parrotlet",
      "Green-Cheeked Conure",
      "Hahn’s Macaw",
      "Eclectus Parrot",
    ],
    Rabbit: [
      "Holland Lop",
      "Mini Lop",
      "Dutch",
      "Lionhead",
      "French Lop",
      "Californian",
      "Dwarf Papillon",
      "Netherland Dwarf",
      "Mini Rex",
      "Flemish Giant",
    ],
};
export default Breeds